### ISSUE TITLE
New image for presentation

### ISSUE THREAD

**Issue by phantom-playR** [moonlight-stream/moonlight-stream.github.io#10]
Hello, on the website the steam BigPicture image is outdated, so I made a new one, with a variant
![steam_framed](https://user-images.githubusercontent.com/4344835/29405430-2f646642-833e-11e7-9edb-eb4a8f6eebfa.png)
![steam_framed3](https://user-images.githubusercontent.com/4344835/29405660-d40c4dea-833e-11e7-8d91-6ab0561f1259.png)

**Comment by cgutman** [comment]
These look really nice. I replaced our old images with the first one. Thanks for the contribution.
