### ISSUE TITLE
Download buttons look terrible

### ISSUE THREAD

**Issue by mrb113** [moonlight-stream/moonlight-stream.github.io#3]
Thanks Cameron :) @cgutman

**Comment by mrb113** [comment]
![image](https://cloud.githubusercontent.com/assets/1258037/8735534/6d8e709c-2bc6-11e5-9418-bb9309cf0025.png)
As much as I hate this, I don't know the first thing about web dev and resent being the defacto "webmaster". Someone who doesn't write drivers for a living and/or knows how to fix it... help!

**Comment by Aghassi** [comment]
I do web dev.

It looks like you need a grid system. What are you using as a framework?

~David Aghassi

**Comment by mrb113** [comment]
David to the rescue! I am using a template which has CSS and HTML. I don't know if that was the answer you were looking for (see above: I don't know the first thing about this) but feel free to look at the code

**Comment by Aghassi** [comment]
Fixed it. You were missing a `div` with a `row` class. It should now be fine. I also pushed formatting fixes.

**Comment by mrb113** [comment]
Thank you @Aghassi :)
