### ISSUE TITLE
Update images to be local copies

### ISSUE THREAD

**Issue by mrb113** [moonlight-stream/moonlight-stream.github.io#5]
We really should not steal Google and Amazon's bandwidth by directly loading their "download from store" images. Please fix

**Comment by Aghassi** [comment]
Just as a side note, I'm pretty sure the dev pages for Amazon and Google will let you download those images for free. I know Apple does.

**Comment by cgutman** [comment]
Fixed in c43c00eda772131614638fddfdda19d008690f30
